export { default as Search } from './search/Search'
export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as PosterCard } from './poster-card/PosterCard'
export { default as Card } from './card/Card'
